# -*- coding: utf-8 -*-
"""MOD2-ebac.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyYgfFNM62yvUnbNNjeglOGe2ACJSKzE

# Ranking de filmes:
Usando o método .append() para adicionar cada título
"""

filmes_lista_dicio = []

filmes_lista_dicio.append({'titulo':'Um Sonho de Liberdade', 'ano':'1994', 'idade':'16', 'nota': '9.3'})
filmes_lista_dicio.append({'titulo':'O Poderoso Chefão', 'ano':'1972', 'idade':'14', 'nota':'9.2'})
filmes_lista_dicio.append({'titulo':'Batman: O Cavaleiro das Trevas', 'ano':'2008', 'idade':'12', 'nota':'9.0'})
filmes_lista_dicio.append({'titulo':'O Poderoso Chefão II', 'ano':'1974', 'idade':'14', 'nota':'9.0'})
filmes_lista_dicio.append({'titulo':'12 Homens e uma Sentença', 'ano':'1957', 'idade':'', 'nota':'9.0'})
filmes_lista_dicio.append({'titulo':'A Lista de Schindler', 'ano':'1993', 'idade':'14', 'nota':'9.0'})
filmes_lista_dicio.append({'titulo':'O Senhor dos Anéis: O Retorno do Rei', 'ano':'2003', 'idade':'14', 'nota':'9.0'})
filmes_lista_dicio.append({'titulo':'Pulp Fiction - Tempo de Violência', 'ano':'1994', 'idade':'18', 'nota':'8.9'})
filmes_lista_dicio.append({'titulo':'O Senhor dos Anéis: A Sociedade do Anel', 'ano':'2001', 'idade':'12', 'nota':'8.8'})
filmes_lista_dicio.append({'titulo':'Três Homens em Conflito', 'ano':'1966', 'idade':'14', 'nota':'8.8'})

print(filmes_lista_dicio)

"""# Trabalhando inserção e remoção com dicionários:"""

filmes_lista_dicio.insert(0, {'titulo':'Meu Filme', 'ano':'1985', 'idade':'livre', 'nota':'10'}) # inserção não remove outros itens, apenas reorganiza, "empurrando" os outros.

"""Ou"""

filmes_lista_dicio[0] = {'titulo':'Meu Filme', 'ano':'1985', 'idade':'livre', 'nota':'10'} # dessa forma se substitui um item por outro.

# É possível remover o último item usuando o método .pop(), inclusive impondo condições:
# lista_filmes.pop() if len(lista_filmes) > 9 else None

"""Caso haja erro de redundância com dois itens repetidos, é possível remover a duplicata fazendo a transformação set <-> list: (Não funciona se o item for tipo dicionário)."""

# filmes_set_dicio = set(filmes_lista_dicio)
# filmes_lista_dicio = list(filmes_set_dicio)

print(f'''
Top 10 best movies:
1. {filmes_lista_dicio[0]}
2. {filmes_lista_dicio[1]}
3. {filmes_lista_dicio[2]}
4. {filmes_lista_dicio[3]}
5. {filmes_lista_dicio[4]}
6. {filmes_lista_dicio[5]}
7. {filmes_lista_dicio[6]}
8. {filmes_lista_dicio[7]}
9. {filmes_lista_dicio[8]}
10. {filmes_lista_dicio[9]}
''')

"""Lista com dicionários dentro é perfeito para Pandas:"""

import pandas
df_filmes = pandas.DataFrame(filmes_lista_dicio)
display(df_filmes)
display(df_filmes.info())