# -*- coding: utf-8 -*-
"""import.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N78eN0jaa-1hhiWJ-i-2ZVoPCLnb08SD
"""

import math

potencia = math.pow(10, 3)

print(potencia)

import math

arredondar = 1648.6

print(math.ceil(arredondar)) # arredonda para cima
print(math.floor(arredondar)) # arredonda para baixo

from time import time, sleep

sleep(5) # vai esperar cinco segundos para continuar o script
print(time()) # O resultado da execução é uma série de números que faz sentido para o computador

from datetime import datetime

a = datetime.now()
b = datetime.now().day
c = datetime.now().year # nçao pode juntar day com year.

print(a, b, c)
print(a)
print(b)
print(c)