# -*- coding: utf-8 -*-
"""openpyxl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/160gsoCMw73FtEj0m15MslHk9xT23uW9N
"""

from openpyxl import load_workbook

credito_xlsx = load_workbook(filename='credito.xlsx')
credito = credito_xlsx.active
header = next(credito.values) # listar os cabeçalhos.
print(header)

"""Extraindo uma coluna da tabela:"""

produtos_indice = header.index('qtd_produtos') # index pega o número que indexa o cabeçalho desejado.

produtos = []

for produto in credito.values:
  if produto[produtos_indice] != 'qtd_produtos':
    produtos.append(produto[produtos_indice])

"""Outra forma, mais avançada, de fazer:"""

produtos = [produto[produtos_indice] for produto in credito.values if produto[produtos_indice] != 'qtd_produtos'] # produtos é um conlchete com um laço for...in e uma condição if se quiser deixar o cabeçalho de fora

print(produtos)